//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_SubHead
    {
        public Nullable<int> Account_Code { get; set; }
        public decimal Account_SubCode { get; set; }
        public string Account_Header { get; set; }
        public string Cash_FlowType { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string Affect_all_project { get; set; }
    
        public virtual Acc_Head Acc_Head { get; set; }
    }
}
