//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Sub_SubHead_Receivable
    {
        public decimal Account_Sub_SubCode { get; set; }
        public Nullable<decimal> Receivable_amt { get; set; }
        public string Notes { get; set; }
        public decimal AutoSLNo { get; set; }
    }
}
