//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accademic_Background
    {
        public decimal Auto_SL { get; set; }
        public string EmpCodeNo { get; set; }
        public string Examination { get; set; }
        public string Board { get; set; }
        public string Exm_Group { get; set; }
        public Nullable<decimal> Year_Passing { get; set; }
        public string Result { get; set; }
        public string Marks { get; set; }
    }
}
