//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsReport_date_wise_DrAmt
    {
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string Month_shortFormate { get; set; }
        public decimal Account_Sub_SubCode { get; set; }
        public Nullable<decimal> Dt1 { get; set; }
        public Nullable<decimal> Dt2 { get; set; }
        public Nullable<decimal> Dt3 { get; set; }
        public Nullable<decimal> Dt4 { get; set; }
        public Nullable<decimal> Dt5 { get; set; }
        public Nullable<decimal> Dt6 { get; set; }
        public Nullable<decimal> Dt7 { get; set; }
        public Nullable<decimal> Dt8 { get; set; }
        public Nullable<decimal> Dt9 { get; set; }
        public Nullable<decimal> Dt10 { get; set; }
        public Nullable<decimal> Dt11 { get; set; }
        public Nullable<decimal> Dt12 { get; set; }
        public Nullable<decimal> Dt13 { get; set; }
        public Nullable<decimal> Dt14 { get; set; }
        public Nullable<decimal> Dt15 { get; set; }
        public Nullable<decimal> Dt16 { get; set; }
        public Nullable<decimal> Dt17 { get; set; }
        public Nullable<decimal> Dt18 { get; set; }
        public Nullable<decimal> Dt19 { get; set; }
        public Nullable<decimal> Dt20 { get; set; }
        public Nullable<decimal> Dt21 { get; set; }
        public Nullable<decimal> Dt22 { get; set; }
        public Nullable<decimal> Dt23 { get; set; }
        public Nullable<decimal> Dt24 { get; set; }
        public Nullable<decimal> Dt25 { get; set; }
        public Nullable<decimal> Dt26 { get; set; }
        public Nullable<decimal> Dt27 { get; set; }
        public Nullable<decimal> Dt28 { get; set; }
        public Nullable<decimal> Dt29 { get; set; }
        public Nullable<decimal> Dt30 { get; set; }
        public Nullable<decimal> Dt31 { get; set; }
        public string DrCr { get; set; }
        public decimal AutoSLNo { get; set; }
    }
}
