//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsTransaction_Add_Less
    {
        public Nullable<decimal> DTSLNO { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public string TransactionType { get; set; }
        public string UserID { get; set; }
        public string Dr_Cr { get; set; }
        public Nullable<decimal> LedgerCode { get; set; }
        public string DO_VoucherNo { get; set; }
        public string ClosingStatus { get; set; }
        public string Entry_Ref_No { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
