//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsTransaction
    {
        public Nullable<decimal> DTSLNO { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> VoucherNo_auto { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string CC_Name { get; set; }
        public string DO_VocherNo { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string TransactionType { get; set; }
        public string Comments { get; set; }
        public string UserID { get; set; }
        public string UserID_Edit { get; set; }
        public string ComputerName { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
        public string Cash_Cheque { get; set; }
        public string Dr_Cr { get; set; }
        public string Received_by { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public string ChqNo { get; set; }
        public Nullable<decimal> Dr_Cr_Code { get; set; }
        public string DrawOn { get; set; }
        public string DBStatus { get; set; }
        public string ClosingStatus { get; set; }
        public string Entry_Ref_No { get; set; }
        public decimal Auto_SLNo { get; set; }
        public string FiscalYearID { get; set; }
        public Nullable<decimal> FiscalPeriodID { get; set; }
    
        public virtual Acc_Sub_SubHead Acc_Sub_SubHead { get; set; }
    }
}
