//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsReport_Month_wise
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> Jan_DrAmt { get; set; }
        public Nullable<decimal> Jan_CrAmt { get; set; }
        public Nullable<decimal> Feb_DrAmt { get; set; }
        public Nullable<decimal> Feb_CrAmt { get; set; }
        public Nullable<decimal> Mar_DrAmt { get; set; }
        public Nullable<decimal> Mar_CrAmt { get; set; }
        public Nullable<decimal> Apr_DrAmt { get; set; }
        public Nullable<decimal> Apr_CrAmt { get; set; }
        public Nullable<decimal> May_DrAmt { get; set; }
        public Nullable<decimal> May_CrAmt { get; set; }
        public Nullable<decimal> Jun_DrAmt { get; set; }
        public Nullable<decimal> Jun_CrAmt { get; set; }
        public Nullable<decimal> Jul_DrAmt { get; set; }
        public Nullable<decimal> Jul_CrAmt { get; set; }
        public Nullable<decimal> Aug_DrAmt { get; set; }
        public Nullable<decimal> Aug_CrAmt { get; set; }
        public Nullable<decimal> Sep_DrAmt { get; set; }
        public Nullable<decimal> Sep_CrAmt { get; set; }
        public Nullable<decimal> Oct_DrAmt { get; set; }
        public Nullable<decimal> Oct_CrAmt { get; set; }
        public Nullable<decimal> Nov_DrAmt { get; set; }
        public Nullable<decimal> Nov_CrAmt { get; set; }
        public Nullable<decimal> Dec_DrAmt { get; set; }
        public Nullable<decimal> Dec_CrAmt { get; set; }
        public decimal Sl { get; set; }
    }
}
