//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_SubArea
    {
        public decimal AutoSlNo { get; set; }
        public string ZoneName { get; set; }
        public string EmpCode_ZoneName { get; set; }
        public string AreaName { get; set; }
        public string EmpCode_AreaName { get; set; }
        public string SubAreaName { get; set; }
        public string EmpCode_SubAreaName { get; set; }
        public decimal Account_Sub_SubCode { get; set; }
        public string Comments { get; set; }
    }
}
