//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetList
    {
        public decimal SLNo { get; set; }
        public Nullable<decimal> VoucherNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string Asset_ID { get; set; }
        public string Asset_Name { get; set; }
        public string SupplierID { get; set; }
        public string Model { get; set; }
        public string Serial { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<decimal> CostDolar { get; set; }
        public Nullable<decimal> CostTk { get; set; }
        public string AsstesType { get; set; }
        public string DeptName { get; set; }
        public string Depr_Option { get; set; }
        public Nullable<decimal> Life { get; set; }
        public Nullable<decimal> DeprPercent { get; set; }
        public string Disposal { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public string Notes { get; set; }
        public string Origin { get; set; }
    }
}
