//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public decimal AutoSLNO { get; set; }
        public string EmpCodeNo { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string PMonth { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public Nullable<decimal> Remarks { get; set; }
        public Nullable<decimal> D1 { get; set; }
        public Nullable<decimal> D2 { get; set; }
        public Nullable<decimal> D3 { get; set; }
        public Nullable<decimal> D4 { get; set; }
        public Nullable<decimal> D5 { get; set; }
        public Nullable<decimal> D6 { get; set; }
        public Nullable<decimal> D7 { get; set; }
        public Nullable<decimal> D8 { get; set; }
        public Nullable<decimal> D9 { get; set; }
        public Nullable<decimal> D10 { get; set; }
        public Nullable<decimal> D11 { get; set; }
        public Nullable<decimal> D12 { get; set; }
        public Nullable<decimal> D13 { get; set; }
        public Nullable<decimal> D14 { get; set; }
        public Nullable<decimal> D15 { get; set; }
        public Nullable<decimal> D16 { get; set; }
        public Nullable<decimal> D17 { get; set; }
        public Nullable<decimal> D18 { get; set; }
        public Nullable<decimal> D19 { get; set; }
        public Nullable<decimal> D20 { get; set; }
        public Nullable<decimal> D21 { get; set; }
        public Nullable<decimal> D22 { get; set; }
        public Nullable<decimal> D23 { get; set; }
        public Nullable<decimal> D24 { get; set; }
        public Nullable<decimal> D25 { get; set; }
        public Nullable<decimal> D26 { get; set; }
        public Nullable<decimal> D27 { get; set; }
        public Nullable<decimal> D28 { get; set; }
        public Nullable<decimal> D29 { get; set; }
        public Nullable<decimal> D30 { get; set; }
        public Nullable<decimal> D31 { get; set; }
        public string Status { get; set; }
        public string Duration { get; set; }
        public string LateComeDutation { get; set; }
        public Nullable<decimal> Attendance1 { get; set; }
        public Nullable<decimal> Absense { get; set; }
        public Nullable<decimal> LateCome { get; set; }
        public Nullable<decimal> OnTime { get; set; }
        public Nullable<decimal> Leave { get; set; }
        public Nullable<decimal> OT { get; set; }
    }
}
