//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance_Sheet
    {
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public decimal Account_Code { get; set; }
        public decimal MainCode { get; set; }
        public string Main_Head { get; set; }
        public string Account_Head { get; set; }
        public decimal Account_SubCode { get; set; }
        public string Account_Header { get; set; }
        public decimal Account_Sub_SubCode { get; set; }
        public string Acc_Name { get; set; }
        public decimal Balance { get; set; }
    }
}
