//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        public Nullable<decimal> SLNO { get; set; }
        public string SubItemCode { get; set; }
        public string Book_Name { get; set; }
        public string Translate_Title { get; set; }
        public string BookLanguage { get; set; }
        public string BookSubject { get; set; }
        public string CopyRight { get; set; }
        public string AuthorName1 { get; set; }
        public string AuthorName2 { get; set; }
        public string AuthorName3 { get; set; }
        public string Editor { get; set; }
        public string Translator { get; set; }
        public string Edition { get; set; }
        public string PublisherName { get; set; }
        public string PublisherYear { get; set; }
        public string PublicationPlace { get; set; }
        public Nullable<decimal> Rate_Tk { get; set; }
        public Nullable<decimal> Rate_TK_Cross { get; set; }
        public Nullable<decimal> Book_Page { get; set; }
        public string ISBN { get; set; }
        public string Illustration { get; set; }
        public string Bibliography { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string Book_Master_Category { get; set; }
        public string Book_Category { get; set; }
        public string Book_Sub_Category { get; set; }
        public string Book_Sub_Sub_Category { get; set; }
        public Nullable<System.DateTime> Add_date { get; set; }
        public Nullable<System.DateTime> Edit_date { get; set; }
        public string User_ID { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
