//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public decimal SLNo { get; set; }
        public System.DateTime Pdate { get; set; }
        public Nullable<decimal> Pyear { get; set; }
        public string Pday { get; set; }
        public Nullable<decimal> MonthOfSl { get; set; }
        public Nullable<decimal> Date_value { get; set; }
        public string Holly_purpose { get; set; }
    }
}
