//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeBookIssue
    {
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string ChqBookNo { get; set; }
        public string ChqNo { get; set; }
        public string UserID { get; set; }
        public string Status { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
        public decimal AutoSLNo { get; set; }
    }
}
