//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class COA_Report
    {
        public Nullable<decimal> Account_SubCode { get; set; }
        public decimal Account_Sub_SubCode { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string Affect_all_project { get; set; }
        public Nullable<decimal> PrjCode_Login { get; set; }
    }
}
