//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Info
    {
        public decimal Auto_SlNo { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public decimal CompCode { get; set; }
        public string CompanyName { get; set; }
        public string CompAddress { get; set; }
        public string CompCountry { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string PrjEmail { get; set; }
        public string WebSite { get; set; }
        public string CompanyRegNo { get; set; }
        public string BusinessType { get; set; }
        public string Currency { get; set; }
        public string Comments { get; set; }
        public string VatNo { get; set; }
        public string TinNo { get; set; }
        public string TradeLicence { get; set; }
        public byte[] Logo { get; set; }
    }
}
