//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compair
    {
        public decimal DTSLNO { get; set; }
        public Nullable<decimal> Pyear { get; set; }
        public string PMonth { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public string Account_Header { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<decimal> DrAmount { get; set; }
        public Nullable<decimal> CrAmount { get; set; }
        public Nullable<decimal> PMonthLast { get; set; }
        public Nullable<decimal> DrLast { get; set; }
        public Nullable<decimal> CrLast { get; set; }
        public Nullable<decimal> PyearLast { get; set; }
    }
}
