//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumption_Formula
    {
        public string SubItemCode_FG { get; set; }
        public decimal Quantity_FG { get; set; }
        public string Item_Entity_FG { get; set; }
        public string SubItemCode_RM { get; set; }
        public decimal RM_Percent { get; set; }
        public decimal Quantity_RM { get; set; }
        public string Item_Entity_RM { get; set; }
        public string UserID { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
        public decimal AutoSL { get; set; }
    }
}
