//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public decimal CostCenter_code { get; set; }
        public string CostCenter_Name { get; set; }
        public Nullable<decimal> Opening_bal { get; set; }
        public string Address { get; set; }
        public string Currency { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Phone { get; set; }
        public string MobileNo { get; set; }
        public string Fax { get; set; }
        public string SMS { get; set; }
        public string EMail { get; set; }
        public string Comments { get; set; }
    }
}
