//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter_Transaction
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string CC_Name { get; set; }
        public Nullable<decimal> CostCenter_code { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public string TransactionType { get; set; }
        public string Comments { get; set; }
        public string Dr_Cr { get; set; }
        public string ClosingStatus { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
