//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_centre_Reg
    {
        public decimal CC_code { get; set; }
        public string CC_Name { get; set; }
        public decimal AutoSlNo { get; set; }
        public string PrjCode { get; set; }
    }
}
