//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustInfo
    {
        public decimal SlNo { get; set; }
        public Nullable<System.DateTime> AdDate { get; set; }
        public string BranchCode { get; set; }
        public string AreaCode { get; set; }
        public string CustIDNO { get; set; }
        public string AccType { get; set; }
        public string AccName { get; set; }
        public string CustName { get; set; }
        public string Sex { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Parmanent_Add { get; set; }
        public string Present_Add { get; set; }
        public string PS { get; set; }
        public string CityDistrict { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public string Religion { get; set; }
        public string Occupation { get; set; }
        public string RefAccNo { get; set; }
        public string RefName { get; set; }
        public string UserID { get; set; }
        public decimal AutoSLNo { get; set; }
    }
}
