//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustReg
    {
        public decimal SlNo { get; set; }
        public decimal PYear { get; set; }
        public System.DateTime PDate { get; set; }
        public string CustIDNO { get; set; }
        public string CustAccNo { get; set; }
        public string SubItemName { get; set; }
        public string Rate { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> NoInstallment { get; set; }
        public string PayableInterest { get; set; }
        public string Installment { get; set; }
        public System.DateTime MaturedDate { get; set; }
        public string ChassisNo { get; set; }
        public string RegNo { get; set; }
        public string ModelNo { get; set; }
        public string Color { get; set; }
        public string Comments { get; set; }
    }
}
