//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Absence
    {
        public string EmpCodeNo { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string InTime { get; set; }
        public decimal AutoSLNo { get; set; }
    }
}
