//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public decimal SLNo { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string PMonth { get; set; }
        public Nullable<decimal> HollyFriday { get; set; }
        public Nullable<decimal> Govt_HoliDay { get; set; }
        public Nullable<decimal> WorkingDay { get; set; }
    }
}
