//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GPAC_ERPEntities1 : DbContext
    {
        public GPAC_ERPEntities1()
            : base("name=GPAC_ERPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acc_Head> Acc_Head { get; set; }
        public virtual DbSet<Acc_Sub_SubHead> Acc_Sub_SubHead { get; set; }
        public virtual DbSet<Acc_SubHead> Acc_SubHead { get; set; }
        public virtual DbSet<AccountsTransaction> AccountsTransactions { get; set; }
        public virtual DbSet<AppRole> AppRoles { get; set; }
        public virtual DbSet<AssetList> AssetLists { get; set; }
        public virtual DbSet<BookInfo> BookInfoes { get; set; }
        public virtual DbSet<ChequeBookIssue> ChequeBookIssues { get; set; }
        public virtual DbSet<Company_Info> Company_Info { get; set; }
        public virtual DbSet<Cost_centre_Reg> Cost_centre_Reg { get; set; }
        public virtual DbSet<CostCenter> CostCenters { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<Emp_Loan_Advance> Emp_Loan_Advance { get; set; }
        public virtual DbSet<FiscalYear> FiscalYears { get; set; }
        public virtual DbSet<Footer_Name> Footer_Name { get; set; }
        public virtual DbSet<FormName> FormNames { get; set; }
        public virtual DbSet<Gift_Card_Reg> Gift_Card_Reg { get; set; }
        public virtual DbSet<Godown> Godowns { get; set; }
        public virtual DbSet<HS_Code> HS_Code { get; set; }
        public virtual DbSet<Inv_Sales_Quotation> Inv_Sales_Quotation { get; set; }
        public virtual DbSet<InvenTransaction> InvenTransactions { get; set; }
        public virtual DbSet<Item_Model> Item_Model { get; set; }
        public virtual DbSet<Item_Size> Item_Size { get; set; }
        public virtual DbSet<ItemCode> ItemCodes { get; set; }
        public virtual DbSet<ItemGroup> ItemGroups { get; set; }
        public virtual DbSet<Main_Head> Main_Head { get; set; }
        public virtual DbSet<MLC> MLCs { get; set; }
        public virtual DbSet<MLC_BBLC> MLC_BBLC { get; set; }
        public virtual DbSet<Privilized_Form> Privilized_Form { get; set; }
        public virtual DbSet<Privilized_Module> Privilized_Module { get; set; }
        public virtual DbSet<Privilized_Report> Privilized_Report { get; set; }
        public virtual DbSet<Product_License> Product_License { get; set; }
        public virtual DbSet<Reg_Member> Reg_Member { get; set; }
        public virtual DbSet<Reg_Project> Reg_Project { get; set; }
        public virtual DbSet<RegSubProject> RegSubProjects { get; set; }
        public virtual DbSet<RolePrivilize> RolePrivilizes { get; set; }
        public virtual DbSet<StockReport_DateRange> StockReport_DateRange { get; set; }
        public virtual DbSet<SubItemCode> SubItemCodes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Targetsheet_FinishGoods> Targetsheet_FinishGoods { get; set; }
        public virtual DbSet<Terms_Condition> Terms_Condition { get; set; }
        public virtual DbSet<User_Login> User_Login { get; set; }
        public virtual DbSet<User_Now> User_Now { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<VAT_RegTbl> VAT_RegTbl { get; set; }
        public virtual DbSet<VoucherName> VoucherNames { get; set; }
        public virtual DbSet<VoucherNo> VoucherNoes { get; set; }
        public virtual DbSet<YearClose> YearCloses { get; set; }
        public virtual DbSet<Acc> Accs { get; set; }
        public virtual DbSet<Acc_Sub_SubHead_Payable> Acc_Sub_SubHead_Payable { get; set; }
        public virtual DbSet<Acc_Sub_SubHead_Receivable> Acc_Sub_SubHead_Receivable { get; set; }
        public virtual DbSet<Accademic_Background> Accademic_Background { get; set; }
        public virtual DbSet<Accounts_Budget> Accounts_Budget { get; set; }
        public virtual DbSet<Accounts_YearClose_Data> Accounts_YearClose_Data { get; set; }
        public virtual DbSet<AccountsReport> AccountsReports { get; set; }
        public virtual DbSet<AccountsReport_date_wise_DrAmt> AccountsReport_date_wise_DrAmt { get; set; }
        public virtual DbSet<AccountsReport_Daybook> AccountsReport_Daybook { get; set; }
        public virtual DbSet<AccountsReport_Ledger> AccountsReport_Ledger { get; set; }
        public virtual DbSet<AccountsReport_Month_wise> AccountsReport_Month_wise { get; set; }
        public virtual DbSet<AccountsReport_RP> AccountsReport_RP { get; set; }
        public virtual DbSet<AccountsReport_Trial_Balance> AccountsReport_Trial_Balance { get; set; }
        public virtual DbSet<AccountsTrans_CardSale> AccountsTrans_CardSale { get; set; }
        public virtual DbSet<AccountsTransaction_Add_Less> AccountsTransaction_Add_Less { get; set; }
        public virtual DbSet<AccountsTransaction_Add_Less_DO> AccountsTransaction_Add_Less_DO { get; set; }
        public virtual DbSet<AccountsTransaction_Delete_Edit> AccountsTransaction_Delete_Edit { get; set; }
        public virtual DbSet<AccountTrans_Budget_vs_Expenditure> AccountTrans_Budget_vs_Expenditure { get; set; }
        public virtual DbSet<AccTrans_Closing> AccTrans_Closing { get; set; }
        public virtual DbSet<Area_SubArea> Area_SubArea { get; set; }
        public virtual DbSet<Assets_Deprciation> Assets_Deprciation { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Backup_Edit_Delete> Backup_Edit_Delete { get; set; }
        public virtual DbSet<Balance_Sheet> Balance_Sheet { get; set; }
        public virtual DbSet<Balance_Sheet_Report> Balance_Sheet_Report { get; set; }
        public virtual DbSet<BarCode> BarCodes { get; set; }
        public virtual DbSet<Barcode_Invoice> Barcode_Invoice { get; set; }
        public virtual DbSet<BarCodeReport> BarCodeReports { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<Cash_Ledger_Report> Cash_Ledger_Report { get; set; }
        public virtual DbSet<ChequeTransaction> ChequeTransactions { get; set; }
        public virtual DbSet<COA_Report> COA_Report { get; set; }
        public virtual DbSet<Compair> Compairs { get; set; }
        public virtual DbSet<Consumption_Formula> Consumption_Formula { get; set; }
        public virtual DbSet<CostCenter_Transaction> CostCenter_Transaction { get; set; }
        public virtual DbSet<Costing_Manufracturing> Costing_Manufracturing { get; set; }
        public virtual DbSet<CustInfo> CustInfoes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustReg> CustRegs { get; set; }
        public virtual DbSet<Daily_Absence> Daily_Absence { get; set; }
        public virtual DbSet<DateProtected> DateProtecteds { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Delete_Edit_Info> Delete_Edit_Info { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Emp_Drop> Emp_Drop { get; set; }
        public virtual DbSet<Emp_Experience> Emp_Experience { get; set; }
        public virtual DbSet<Emp_Facilities> Emp_Facilities { get; set; }
        public virtual DbSet<Emp_history> Emp_history { get; set; }
        public virtual DbSet<Emp_Info> Emp_Info { get; set; }
        public virtual DbSet<Emp_Promossion> Emp_Promossion { get; set; }
        public virtual DbSet<Emp_Salary> Emp_Salary { get; set; }
        public virtual DbSet<Emp_Salary_configure> Emp_Salary_configure { get; set; }
        public virtual DbSet<EmpPic> EmpPics { get; set; }
        public virtual DbSet<Export> Exports { get; set; }
        public virtual DbSet<FiscalPeriod> FiscalPeriods { get; set; }
        public virtual DbSet<Gift_Card_Sale> Gift_Card_Sale { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Incentive_Statement> Incentive_Statement { get; set; }
        public virtual DbSet<Inv_Manu_Batch> Inv_Manu_Batch { get; set; }
        public virtual DbSet<Inv_Manu_Process_Consumption> Inv_Manu_Process_Consumption { get; set; }
        public virtual DbSet<Inv_Manu_Process_FinishGoods> Inv_Manu_Process_FinishGoods { get; set; }
        public virtual DbSet<Inv_report> Inv_report { get; set; }
        public virtual DbSet<Inventory_Amount_wise_Monthly_report> Inventory_Amount_wise_Monthly_report { get; set; }
        public virtual DbSet<Inventory_day_wise> Inventory_day_wise { get; set; }
        public virtual DbSet<Inventory_DO> Inventory_DO { get; set; }
        public virtual DbSet<Inventory_Item_wise_Monthly_report> Inventory_Item_wise_Monthly_report { get; set; }
        public virtual DbSet<Inventory_PO> Inventory_PO { get; set; }
        public virtual DbSet<Inventory_Report_Add_Less> Inventory_Report_Add_Less { get; set; }
        public virtual DbSet<Inventory_Update> Inventory_Update { get; set; }
        public virtual DbSet<InventoryTransaction_Delete_Edit> InventoryTransaction_Delete_Edit { get; set; }
        public virtual DbSet<InvenTransaction_Estimate> InvenTransaction_Estimate { get; set; }
        public virtual DbSet<Item_Color> Item_Color { get; set; }
        public virtual DbSet<Item_Design> Item_Design { get; set; }
        public virtual DbSet<Item_Ledger_Report> Item_Ledger_Report { get; set; }
        public virtual DbSet<Item_Picture> Item_Picture { get; set; }
        public virtual DbSet<ItemStyle> ItemStyles { get; set; }
        public virtual DbSet<ItemWise_Supplier> ItemWise_Supplier { get; set; }
        public virtual DbSet<LeaveLedger> LeaveLedgers { get; set; }
        public virtual DbSet<Ledger> Ledgers { get; set; }
        public virtual DbSet<LegerReport> LegerReports { get; set; }
        public virtual DbSet<Loan_Application> Loan_Application { get; set; }
        public virtual DbSet<Loan_DataEntry> Loan_DataEntry { get; set; }
        public virtual DbSet<LoanSchedule> LoanSchedules { get; set; }
        public virtual DbSet<LoanSchemeReg> LoanSchemeRegs { get; set; }
        public virtual DbSet<Manufracturing_Admin_cost> Manufracturing_Admin_cost { get; set; }
        public virtual DbSet<Manufracturing_cost_report> Manufracturing_cost_report { get; set; }
        public virtual DbSet<Member_Point> Member_Point { get; set; }
        public virtual DbSet<MLC_PO> MLC_PO { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Monthly_Att_Statement> Monthly_Att_Statement { get; set; }
        public virtual DbSet<National_report> National_report { get; set; }
        public virtual DbSet<Nominee> Nominees { get; set; }
        public virtual DbSet<OverTime> OverTimes { get; set; }
        public virtual DbSet<OverTime_Report> OverTime_Report { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Package_Commision> Package_Commision { get; set; }
        public virtual DbSet<PackageSale> PackageSales { get; set; }
        public virtual DbSet<PE_Form> PE_Form { get; set; }
        public virtual DbSet<PF_DataEntry> PF_DataEntry { get; set; }
        public virtual DbSet<POS_configure> POS_configure { get; set; }
        public virtual DbSet<Primary_Target> Primary_Target { get; set; }
        public virtual DbSet<Professional_Degree> Professional_Degree { get; set; }
        public virtual DbSet<Project_Costing> Project_Costing { get; set; }
        public virtual DbSet<Purchase_Add_Less> Purchase_Add_Less { get; set; }
        public virtual DbSet<Purchase_Costing> Purchase_Costing { get; set; }
        public virtual DbSet<Purchase_vs_Estimate> Purchase_vs_Estimate { get; set; }
        public virtual DbSet<QInOutTime_Data> QInOutTime_Data { get; set; }
        public virtual DbSet<Re_Order_report> Re_Order_report { get; set; }
        public virtual DbSet<Receipt_payment> Receipt_payment { get; set; }
        public virtual DbSet<Reg_OrderNo> Reg_OrderNo { get; set; }
        public virtual DbSet<RegParty> RegParties { get; set; }
        public virtual DbSet<Report_Statement> Report_Statement { get; set; }
        public virtual DbSet<Salary_Sheet_Final> Salary_Sheet_Final { get; set; }
        public virtual DbSet<SalaryStatement_> SalaryStatement_ { get; set; }
        public virtual DbSet<Sale_Add_Less> Sale_Add_Less { get; set; }
        public virtual DbSet<Sales_Quotation_Template> Sales_Quotation_Template { get; set; }
        public virtual DbSet<Sales_Target_Report> Sales_Target_Report { get; set; }
        public virtual DbSet<SalesTarget> SalesTargets { get; set; }
        public virtual DbSet<SMS_Transaction> SMS_Transaction { get; set; }
        public virtual DbSet<StaffPicture> StaffPictures { get; set; }
        public virtual DbSet<Stock_Transfer> Stock_Transfer { get; set; }
        public virtual DbSet<SubItemSLNo> SubItemSLNoes { get; set; }
        public virtual DbSet<Trading_Acc_Report> Trading_Acc_Report { get; set; }
        public virtual DbSet<Trading_Acc_Report_Manufracturing> Trading_Acc_Report_Manufracturing { get; set; }
        public virtual DbSet<TradingAcc_2015> TradingAcc_2015 { get; set; }
        public virtual DbSet<Trail_Balance_Report> Trail_Balance_Report { get; set; }
        public virtual DbSet<User_Parameter> User_Parameter { get; set; }
        public virtual DbSet<User_Privilized> User_Privilized { get; set; }
        public virtual DbSet<VoucherType> VoucherTypes { get; set; }
        public virtual DbSet<Work_Order_Producer> Work_Order_Producer { get; set; }
        public virtual DbSet<Work_Order_Vs_Receipt> Work_Order_Vs_Receipt { get; set; }
        public virtual DbSet<working_progress> working_progress { get; set; }
        public virtual DbSet<WorkingDay> WorkingDays { get; set; }
    }
}
