//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public decimal SlNo { get; set; }
        public string Grade { get; set; }
        public string Designation1 { get; set; }
        public string OT_status { get; set; }
        public string OT_amt_Hr { get; set; }
        public string OT_amt_Hr_Hollyday { get; set; }
        public Nullable<decimal> LedgerCode { get; set; }
    }
}
