//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_history
    {
        public string EMPCodeNo { get; set; }
        public decimal Total_Salary { get; set; }
        public string Designation { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
