//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Loan_Advance
    {
        public string EmpCodeNo { get; set; }
        public System.DateTime Application_date { get; set; }
        public System.DateTime LoanIssueDate { get; set; }
        public string LoanPurpose { get; set; }
        public decimal Loan_amount { get; set; }
        public string LoanNo { get; set; }
        public decimal InstallmentNo { get; set; }
        public decimal Monthly_Installment { get; set; }
        public string LoanStatus { get; set; }
        public string comments { get; set; }
    }
}
