//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Promossion
    {
        public string EmpCodeNo { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string Department_Old { get; set; }
        public string Designation_Old { get; set; }
        public Nullable<decimal> Salary_Old { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> IncreaseSalary { get; set; }
    }
}
