//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Info
    {
        public decimal SlNo { get; set; }
        public Nullable<System.DateTime> Application_date { get; set; }
        public Nullable<System.DateTime> JoingDate { get; set; }
        public Nullable<System.DateTime> ConfermationDate { get; set; }
        public decimal PrjCode { get; set; }
        public string EmpCodeNo { get; set; }
        public string EmpName { get; set; }
        public string EmpNameBangla { get; set; }
        public string Department { get; set; }
        public string Grade { get; set; }
        public string Sex { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string Marital_Status { get; set; }
        public string Spouse_Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string PS { get; set; }
        public string City_District { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
        public string Mobile_No { get; set; }
        public string PassportNo { get; set; }
        public string BirthCerNo { get; set; }
        public string DrivingLicenceNo { get; set; }
        public string NationalIDNo { get; set; }
        public string BloodGrp { get; set; }
        public string Tel { get; set; }
        public string Mail { get; set; }
        public string EMP_Religion { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Designation { get; set; }
        public string Job_type { get; set; }
        public string EMP_type { get; set; }
        public string RefName1 { get; set; }
        public string RefAddress1 { get; set; }
        public string RefMob1 { get; set; }
        public string RefName2 { get; set; }
        public string RefAddress2 { get; set; }
        public string RefMob2 { get; set; }
        public string JobStatus { get; set; }
        public string Notes { get; set; }
        public string JobCardNo { get; set; }
        public Nullable<decimal> LedgerCode { get; set; }
    }
}
