//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Facilities
    {
        public string EmpCodeNo { get; set; }
        public string MobileHandSet { get; set; }
        public string SimNo { get; set; }
        public string Car { get; set; }
        public string Driver { get; set; }
        public string Others { get; set; }
    }
}
