//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Experience
    {
        public decimal Auto_SL { get; set; }
        public string EmpCodeNo { get; set; }
        public string Organization_Name { get; set; }
        public string Organization_Address { get; set; }
        public string Period_Emp { get; set; }
        public string Position_Held { get; set; }
        public string Responsibilities { get; set; }
    }
}
