//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Salary_configure
    {
        public string Designation { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> House_Rent { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> PF_less { get; set; }
        public Nullable<decimal> PF_add { get; set; }
        public Nullable<decimal> Income_Tax { get; set; }
        public Nullable<decimal> Increment_amt { get; set; }
        public decimal AutoSL { get; set; }
    }
}
