//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Drop
    {
        public string EmpCodeNo { get; set; }
        public Nullable<System.DateTime> Resign_date { get; set; }
        public Nullable<System.DateTime> Approve_date { get; set; }
        public string Reson_Resign { get; set; }
        public string Comments { get; set; }
    }
}
