//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Salary
    {
        public Nullable<decimal> PYear { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string EmpCodeNo { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> House_Rent { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> PF_Less { get; set; }
        public Nullable<decimal> PF_Add { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Income_Tax { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> Phone_Bill { get; set; }
        public Nullable<decimal> Total_Salary { get; set; }
        public string OT_status { get; set; }
        public Nullable<decimal> OT_Per_HR { get; set; }
        public string Comments { get; set; }
        public string Salary_status { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
        public string UserID { get; set; }
        public decimal AutoSL { get; set; }
    }
}
