//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<System.DateTime> Exp_Date { get; set; }
        public Nullable<decimal> VoucherNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string MLCNo { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public string BBLCNo { get; set; }
        public Nullable<System.DateTime> BBDate { get; set; }
        public Nullable<decimal> BBLCTotCost { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
