//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift_Card_Reg
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public decimal Gift_CardNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
