//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift_Card_Sale
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public string Gift_CardNo { get; set; }
        public string ClentName { get; set; }
        public string PrjName { get; set; }
        public string MobileNo { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> VoucherNo_auto { get; set; }
        public Nullable<decimal> Dr_Amt { get; set; }
        public Nullable<decimal> Cr_Amt { get; set; }
        public string UserID { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
