//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public decimal SL { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string Grade1 { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> Increase_salary { get; set; }
    }
}
