//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HS_Code
    {
        public string HSCODE { get; set; }
        public string SubItemName { get; set; }
        public Nullable<decimal> CD { get; set; }
        public Nullable<decimal> SD { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> AIT { get; set; }
        public Nullable<decimal> RD { get; set; }
        public Nullable<decimal> ATV { get; set; }
        public Nullable<decimal> TTI { get; set; }
        public Nullable<decimal> EXD { get; set; }
    }
}
