//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_report
    {
        public decimal Auto_SLNo { get; set; }
        public System.DateTime PDate { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string Exp_Date { get; set; }
        public string PONo { get; set; }
        public Nullable<decimal> VoucherNo { get; set; }
        public string VoucherNo_Type { get; set; }
        public decimal TransNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string MLCNo { get; set; }
        public string GodownNo { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> SubItemCode { get; set; }
        public Nullable<decimal> Estimate { get; set; }
        public Nullable<decimal> In_Item { get; set; }
        public Nullable<decimal> Out_Item { get; set; }
        public string Item_Entity { get; set; }
        public Nullable<decimal> Bal_Item { get; set; }
        public Nullable<decimal> Rate_Per_Item { get; set; }
        public string CurrancyCode { get; set; }
        public Nullable<decimal> Currancy_Rate_Per_Item { get; set; }
        public Nullable<decimal> LocalRate { get; set; }
        public Nullable<decimal> Commision { get; set; }
        public Nullable<decimal> TotalCommision { get; set; }
        public Nullable<decimal> Total_amt_FrnCurrancy { get; set; }
        public Nullable<decimal> Total_amt { get; set; }
        public string TransactionType { get; set; }
        public string ItemType { get; set; }
        public string Comments { get; set; }
        public string UserID { get; set; }
        public string ComputerName { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
    }
}
