//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Manu_Process_FinishGoods
    {
        public Nullable<decimal> PrjCode { get; set; }
        public string PorcessName { get; set; }
        public Nullable<decimal> SubItemCode { get; set; }
        public Nullable<decimal> Qnt { get; set; }
        public string Unit { get; set; }
        public string AddDate_time { get; set; }
        public string UserID { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
