//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Manu_Batch
    {
        public decimal VoucherNo { get; set; }
        public string INV_LOG_NO { get; set; }
        public Nullable<System.DateTime> Str_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public Nullable<System.DateTime> Exp_date { get; set; }
        public Nullable<System.DateTime> Manu_date { get; set; }
        public string Acc_sub_subcode { get; set; }
        public string Status { get; set; }
        public string Add_date { get; set; }
        public string Edit_date { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
