//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Report_Add_Less
    {
        public Nullable<decimal> Accounts_Sub_SubCode { get; set; }
        public Nullable<decimal> LedgerCode { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public string TransactionType { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
