//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Amount_wise_Monthly_report
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string SubItemCode { get; set; }
        public Nullable<decimal> Qnty { get; set; }
        public string TransactionType { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<decimal> Total_amt_Jan { get; set; }
        public Nullable<decimal> Total_amt_Feb { get; set; }
        public Nullable<decimal> Total_amt_Mar { get; set; }
        public Nullable<decimal> Total_amt_Apr { get; set; }
        public Nullable<decimal> Total_amt_May { get; set; }
        public Nullable<decimal> Total_amt_Jun { get; set; }
        public Nullable<decimal> Total_amt_Jul { get; set; }
        public Nullable<decimal> Total_amt_Aug { get; set; }
        public Nullable<decimal> Total_amt_Sep { get; set; }
        public Nullable<decimal> Total_amt_Oct { get; set; }
        public Nullable<decimal> Total_amt_Nov { get; set; }
        public Nullable<decimal> Total_amt_Dec { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
