//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveLedger
    {
        public string EmpCodeNo { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string PMonth { get; set; }
        public string PYear { get; set; }
        public Nullable<System.DateTime> StrDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> EarnedDr { get; set; }
        public Nullable<decimal> EarnedCr { get; set; }
        public Nullable<decimal> EarnedBal { get; set; }
        public Nullable<decimal> CasualDr { get; set; }
        public Nullable<decimal> CasualCr { get; set; }
        public Nullable<decimal> CasualBal { get; set; }
        public Nullable<decimal> MedicalDr { get; set; }
        public Nullable<decimal> MedicalCr { get; set; }
        public Nullable<decimal> MedicalBal { get; set; }
        public Nullable<decimal> MetanityDr { get; set; }
        public Nullable<decimal> MetanityCr { get; set; }
        public Nullable<decimal> MetanityBal { get; set; }
        public Nullable<decimal> OtherCr { get; set; }
        public Nullable<decimal> WithoutPay { get; set; }
        public Nullable<decimal> OfficeDuty { get; set; }
        public string Comments { get; set; }
    }
}
