//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSchemeReg
    {
        public string LaonSchemeCode { get; set; }
        public string SchemeName { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
    }
}
