//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanSchedule
    {
        public decimal AutoSLNo { get; set; }
        public decimal SlNo { get; set; }
        public Nullable<System.DateTime> PayableDate { get; set; }
        public string LoanNo { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> AmtOfInstallment { get; set; }
    }
}
