//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_DataEntry
    {
        public decimal SlNo { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> VoucherNo { get; set; }
        public string LoanNo { get; set; }
        public decimal EntryNo { get; set; }
        public Nullable<decimal> LedgerCode { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public Nullable<decimal> Bal { get; set; }
        public string Notes { get; set; }
        public string TransactionType { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<decimal> CustAccTrSL { get; set; }
        public string AddDate { get; set; }
        public string Editdate { get; set; }
        public string StaffID { get; set; }
        public string UserId { get; set; }
    }
}
