//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Application
    {
        public decimal AutoSlNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<decimal> VoucherNo { get; set; }
        public string CustName { get; set; }
        public string Account_Sub_SubCode { get; set; }
        public string GurantorName { get; set; }
        public string FlatCode { get; set; }
        public Nullable<decimal> FlatRate { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> RateofInterest { get; set; }
        public Nullable<decimal> PayableInterest { get; set; }
        public Nullable<decimal> Total_amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Net_Payable_amt { get; set; }
        public Nullable<decimal> Total_Flat_amt { get; set; }
        public Nullable<decimal> Installment { get; set; }
        public Nullable<decimal> Period { get; set; }
        public Nullable<decimal> AmtOfInstment { get; set; }
        public string RecoveryStatus { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string SpecialOrder { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public string EmpCodeNo { get; set; }
        public string UserID { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
    }
}
