//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Head
    {
        public decimal MainCode { get; set; }
        public string Account_Head { get; set; }
        public Nullable<decimal> Sl { get; set; }
        public string Dr_Cr { get; set; }
    }
}
