//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufracturing_cost_report
    {
        public string OrderNo { get; set; }
        public string SubItemCode { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string Particulars { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> Out_Item { get; set; }
        public Nullable<decimal> Rate_Per_Item { get; set; }
        public string Item_Entity { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
