//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufracturing_Admin_cost
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string OrderNo { get; set; }
        public string SubItemCode { get; set; }
        public string Particulars { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<decimal> VoucherNo_auto { get; set; }
        public string TransactionType { get; set; }
        public string ClosingStatus { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
