//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Point
    {
        public System.DateTime PDate { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public decimal Member_ID { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> Dr_Point { get; set; }
        public Nullable<decimal> Cr_Point { get; set; }
        public Nullable<decimal> Cr_Amt { get; set; }
        public string UserID { get; set; }
        public decimal AutoSlNo { get; set; }
        public string MemberType { get; set; }
    }
}
