//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLC
    {
        public decimal SLNo { get; set; }
        public string MLCNo { get; set; }
        public Nullable<System.DateTime> LCDate { get; set; }
        public string MLCType { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public string BuyerName { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> MLC_ExpDate { get; set; }
        public string BankName { get; set; }
        public string IssueBank { get; set; }
        public string OpeningBank { get; set; }
        public string MLC_Currancy { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> MLC_Rate { get; set; }
        public Nullable<decimal> MLC_TotTk { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetLCAmount { get; set; }
        public Nullable<decimal> BuyerCommission { get; set; }
        public string Shipping_mode { get; set; }
        public Nullable<decimal> Shipping_mode_amt { get; set; }
    }
}
