//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLC_BBLC
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public string MLCNo { get; set; }
        public string BBLCNo { get; set; }
        public string Acc_Name { get; set; }
        public decimal Account_Sub_SubCode { get; set; }
        public Nullable<decimal> SubItemCode { get; set; }
        public Nullable<decimal> BBLCQnt { get; set; }
        public Nullable<decimal> BBLCUnitCost { get; set; }
        public Nullable<decimal> BBLCTotCost { get; set; }
        public string BBLCDesc { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
