//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class National_report
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public string PMonth { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public Nullable<decimal> SubItemCode { get; set; }
        public Nullable<decimal> Rate_Per_Item { get; set; }
        public Nullable<decimal> OpeningStock { get; set; }
        public Nullable<decimal> Total_sale { get; set; }
        public Nullable<decimal> Total_stock { get; set; }
        public Nullable<decimal> Secondary_Sale { get; set; }
        public Nullable<decimal> ClosingStock { get; set; }
        public decimal AutoSL { get; set; }
    }
}
