//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominee
    {
        public string CustIdNo { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public string Age1 { get; set; }
        public string Age2 { get; set; }
        public string Age3 { get; set; }
        public string Age4 { get; set; }
        public string Guardians1 { get; set; }
        public string Guardians2 { get; set; }
        public string Guardians3 { get; set; }
        public string Guardians4 { get; set; }
        public string Percent1 { get; set; }
        public string Percent2 { get; set; }
        public string Percent3 { get; set; }
        public string Percent4 { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Relation1 { get; set; }
        public string Relation2 { get; set; }
        public string Relation3 { get; set; }
        public string Relation4 { get; set; }
    }
}
