//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverTime
    {
        public Nullable<decimal> PrjCode { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> VoucherNo_auto { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string PMonth { get; set; }
        public string EmpCodeNo { get; set; }
        public Nullable<decimal> OT_Hr { get; set; }
        public Nullable<decimal> OT_Per_HR { get; set; }
        public Nullable<decimal> OT_amt { get; set; }
        public decimal AutoSLNo { get; set; }
    }
}
