//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageSale
    {
        public decimal AutoSLNo { get; set; }
        public string InstituteName { get; set; }
        public string ClassName { get; set; }
        public string SubItemCode { get; set; }
        public Nullable<decimal> Out_Item { get; set; }
    }
}
