//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Commision
    {
        public decimal AutoSLNo { get; set; }
        public Nullable<decimal> Packge_Commision { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string UserID { get; set; }
    }
}
