//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PE_Form
    {
        public decimal AutoSLNO { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string PMonth { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string EmpCodeNo { get; set; }
        public string Department { get; set; }
        public string GRADE { get; set; }
        public Nullable<decimal> TotNumber { get; set; }
        public string Reporting_Officer { get; set; }
        public Nullable<decimal> Increase_Salary { get; set; }
    }
}
