//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PF_DataEntry
    {
        public string PYear { get; set; }
        public Nullable<decimal> CustAccTrSL { get; set; }
        public System.DateTime PDate { get; set; }
        public string PMonth { get; set; }
        public string BranchCode { get; set; }
        public string EmpCodeNo { get; set; }
        public Nullable<decimal> DailyTransNo { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public Nullable<decimal> Bal { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> PrfStatus { get; set; }
        public string TransactionType { get; set; }
        public string TransactionStatus { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
        public string UserName { get; set; }
        public string User_Id { get; set; }
        public string DBStatus { get; set; }
        public decimal SlNo { get; set; }
    }
}
