//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_configure
    {
        public decimal AutoSLNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public decimal VAT { get; set; }
        public decimal GodownNo { get; set; }
        public decimal AddDr_AccCode { get; set; }
        public decimal Account_Sub_SubCode { get; set; }
        public string Supplier_wise_Item { get; set; }
    }
}
