//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Primary_Target
    {
        public decimal AutoSL { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> TransNo { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> SubItemCode { get; set; }
        public Nullable<decimal> Rate_Per_Item { get; set; }
        public Nullable<decimal> TargetQnt { get; set; }
        public Nullable<decimal> Out_Item { get; set; }
        public Nullable<decimal> Total_amt { get; set; }
        public string TransactionType { get; set; }
        public string Comments { get; set; }
        public string UserID { get; set; }
        public string ComputerName { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
    }
}
