//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilized_Form
    {
        public decimal SLNO { get; set; }
        public string FormName { get; set; }
        public string FormType { get; set; }
        public string FormGroups { get; set; }
        public string Packages { get; set; }
    }
}
