//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilized_Report
    {
        public Nullable<decimal> SLNO { get; set; }
        public string ReportName { get; set; }
        public string ReportType { get; set; }
        public string ReportGroups { get; set; }
        public string Packages { get; set; }
    }
}
