//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilized_Module
    {
        public string ModuleName { get; set; }
        public string ModuleType { get; set; }
        public string ModuleLink { get; set; }
        public string Packages { get; set; }
        public Nullable<decimal> SLNO { get; set; }
    }
}
