//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional_Degree
    {
        public decimal Auto_SL { get; set; }
        public string Std_IDNO { get; set; }
        public string Institute { get; set; }
        public string Course { get; set; }
        public string Degree { get; set; }
        public string Grade { get; set; }
    }
}
