//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Costing
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> VoucherNo { get; set; }
        public string BatchNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> Qnt { get; set; }
        public Nullable<decimal> Rate_Per_Item { get; set; }
        public Nullable<decimal> Total_amt { get; set; }
        public string TransactionType { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
