//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_vs_Estimate
    {
        public decimal Auto_SLNo { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string SubItemCode { get; set; }
        public Nullable<decimal> Estimate_qnty { get; set; }
        public Nullable<decimal> Purchase_qnty { get; set; }
        public Nullable<decimal> Estimate_Total_amt { get; set; }
        public Nullable<decimal> Purchase_Total_amt { get; set; }
    }
}
