//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QInOutTime_Data
    {
        public Nullable<System.DateTime> sdate { get; set; }
        public string cardnum { get; set; }
        public string stime_In { get; set; }
        public string stime_out { get; set; }
        public decimal AgyrSL { get; set; }
    }
}
