//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Order_report
    {
        public decimal Account_Sub_SubCode { get; set; }
        public string Acc_Name { get; set; }
        public string SubItemCode { get; set; }
        public Nullable<decimal> stock { get; set; }
    }
}
