//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Member
    {
        public Nullable<System.DateTime> RegDate { get; set; }
        public decimal Member_ID { get; set; }
        public string Member_Name { get; set; }
        public string Member_Category { get; set; }
        public string F_Name { get; set; }
        public string M_Name { get; set; }
        public string Mailing_Addr { get; set; }
        public string Mobile_No { get; set; }
        public string EMail { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> MemDOB { get; set; }
        public string Institute_Org { get; set; }
        public string Class_Designation { get; set; }
        public string BloodGrp { get; set; }
        public Nullable<decimal> Ref_Member_ID { get; set; }
        public string Ref_Member_Name { get; set; }
        public string Hobby { get; set; }
        public string Interest { get; set; }
        public string Gender { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
