//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_OrderNo
    {
        public string OrderNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string SubItemCode_FG { get; set; }
        public Nullable<decimal> Quantity_FG { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string Comments { get; set; }
        public string OrderStatus { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
