//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Project
    {
        public decimal Auto_SlNo { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> CompCode { get; set; }
        public decimal PrjCode { get; set; }
        public string PrjName { get; set; }
        public string PrjAddress { get; set; }
        public string PrjCountry { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string PrjEMail { get; set; }
        public string WebSite { get; set; }
        public string BusinessType { get; set; }
        public string Currency { get; set; }
        public string Comments { get; set; }
        public string Exp_PDate { get; set; }
        public string Package { get; set; }
        public string FileName { get; set; }
        public byte[] Logo { get; set; }
    }
}
