//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegParty
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public decimal PartyCode { get; set; }
        public string OffName { get; set; }
        public string Owner { get; set; }
        public string Addr { get; set; }
        public string PS { get; set; }
        public string Dist { get; set; }
        public string SubAreaCode { get; set; }
        public string Phone { get; set; }
        public string Mob { get; set; }
        public string Mail { get; set; }
        public string ContPer { get; set; }
        public string Transaport { get; set; }
        public string Status { get; set; }
        public decimal Account_Sub_SubCode { get; set; }
        public string Bank_Name_Acc { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string Active { get; set; }
        public decimal Auto_SLNo { get; set; }
    }
}
