//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegSubProject
    {
        public decimal AutoSLNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string FlatCode { get; set; }
        public Nullable<decimal> FlatSize { get; set; }
        public Nullable<decimal> FlatRate_Sft { get; set; }
        public Nullable<decimal> FlatAmount { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public string Comments { get; set; }
    }
}
