//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Statement
    {
        public System.DateTime CDate { get; set; }
        public string CTime { get; set; }
        public string User_ID { get; set; }
        public string Report_Name { get; set; }
        public string Comp_Name { get; set; }
        public string IP_addr { get; set; }
        public decimal AutoSLNo { get; set; }
    }
}
