//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePrivilize
    {
        public string Id { get; set; }
        public string RoleId { get; set; }
        public string DocType { get; set; }
        public string DocName { get; set; }
        public bool RecView { get; set; }
        public bool RecAdd { get; set; }
        public bool RecEdit { get; set; }
        public bool RecDel { get; set; }
        public bool Inventory_Entry_ItemCode_wise { get; set; }
    }
}
