//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_Sheet_Final
    {
        public Nullable<decimal> PrjCode { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string EmpCodeNo { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public string EmpName { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> PYear { get; set; }
        public string PMonth { get; set; }
        public Nullable<decimal> Total_Attendance { get; set; }
        public Nullable<decimal> HollyDay { get; set; }
        public Nullable<decimal> LateCome { get; set; }
        public Nullable<decimal> OnTime { get; set; }
        public Nullable<decimal> OT { get; set; }
        public Nullable<decimal> EL { get; set; }
        public Nullable<decimal> CL { get; set; }
        public Nullable<decimal> ML { get; set; }
        public Nullable<decimal> OL { get; set; }
        public Nullable<decimal> WP { get; set; }
        public Nullable<decimal> OD { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> House_Rent { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> PF_Less { get; set; }
        public Nullable<decimal> PF_Add { get; set; }
        public Nullable<decimal> Income_Tax { get; set; }
        public Nullable<decimal> Total_Salary { get; set; }
        public Nullable<decimal> OT_Per_HR { get; set; }
        public Nullable<decimal> Monthly_Installment { get; set; }
        public Nullable<decimal> WP_amt { get; set; }
        public Nullable<decimal> Phone_bill { get; set; }
        public Nullable<decimal> NetSalary_Payable { get; set; }
        public string JobStatus { get; set; }
        public string DB_status { get; set; }
        public Nullable<decimal> OT_amt { get; set; }
        public string LoanNo { get; set; }
        public Nullable<decimal> LedgerCode { get; set; }
        public decimal AutoSL { get; set; }
    }
}
