//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Target_Report
    {
        public Nullable<System.DateTime> PDate { get; set; }
        public string SubAreaName { get; set; }
        public Nullable<decimal> SubItemCode { get; set; }
        public Nullable<decimal> Secondery_Target_qnt { get; set; }
        public Nullable<decimal> Secondery_Achivement_qnt { get; set; }
        public Nullable<decimal> Rate_Per_Item { get; set; }
        public Nullable<decimal> Target_Amount { get; set; }
        public Nullable<decimal> Achivement_Amount { get; set; }
        public string Status { get; set; }
        public decimal AutoSL { get; set; }
    }
}
