//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Quotation_Template
    {
        public decimal AutoSLNO { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Terms_Condition { get; set; }
        public string Footer { get; set; }
        public string Abc2 { get; set; }
    }
}
