//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubItemCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubItemCode()
        {
            this.InvenTransactions = new HashSet<InvenTransaction>();
        }
    
        public decimal Auto_SLNO { get; set; }
        public decimal ItemCode { get; set; }
        public string SubItemCode1 { get; set; }
        public string SubItemName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> ClosingPrice { get; set; }
        public string Item_Entity { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public string ItemType { get; set; }
        public Nullable<decimal> MinimumStock { get; set; }
        public Nullable<decimal> OpeningStock { get; set; }
        public Nullable<decimal> Pcs_Pack { get; set; }
        public string Pcs_Pack_Entity { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string ItemStyleName { get; set; }
        public string ModelName { get; set; }
        public string Item_Size { get; set; }
        public decimal ItemSLNo { get; set; }
        public Nullable<decimal> AskingPrice { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string Affect_all_project { get; set; }
        public string SubItemName_Bangla { get; set; }
        public string HSCode { get; set; }
        public string SubItemName_Commercial { get; set; }
        public string Nature_of_supply { get; set; }
        public string Nature_of_purchase { get; set; }
        public Nullable<decimal> Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvenTransaction> InvenTransactions { get; set; }
        public virtual ItemCode ItemCode1 { get; set; }
    }
}
