//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Targetsheet_FinishGoods
    {
        public string OrderNo { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public decimal OrderSlNo { get; set; }
        public string SubItemCode { get; set; }
        public string Design_Desc { get; set; }
        public decimal Target_Qnt { get; set; }
        public string Unit { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public string EmpCodeNo { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
