//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terms_Condition
    {
        public string VoucherNo { get; set; }
        public string T_C { get; set; }
        public string MOP { get; set; }
        public string Warranty { get; set; }
        public string Add_Date_time { get; set; }
        public string Edit_Date_time { get; set; }
        public string Add_UserId { get; set; }
        public string Edit_UserId { get; set; }
        public string TrnsType { get; set; }
        public decimal AutoSLNo { get; set; }
    }
}
