//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingAcc_2015
    {
        public decimal Sl { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string TransactionType { get; set; }
        public string Acc_Name { get; set; }
        public Nullable<decimal> Bal { get; set; }
        public Nullable<decimal> Total_Balance { get; set; }
        public decimal Account_SubCode { get; set; }
        public string Account_Header { get; set; }
    }
}
