//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trading_Acc_Report_Manufracturing
    {
        public Nullable<decimal> PrjCode { get; set; }
        public Nullable<decimal> Amount_OpeningStock { get; set; }
        public Nullable<decimal> Amount_Purchase { get; set; }
        public Nullable<decimal> Amount_Sale { get; set; }
        public Nullable<decimal> Amount_SaleReturn { get; set; }
        public Nullable<decimal> Amount_StockDamage { get; set; }
        public Nullable<decimal> Amount_StockValue { get; set; }
        public Nullable<decimal> Amount_WIP { get; set; }
        public decimal AutoSlNo { get; set; }
    }
}
