//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Privilized
    {
        public decimal SLNO { get; set; }
        public string User_ID { get; set; }
        public string Type { get; set; }
        public string Privilized_Form_Report { get; set; }
        public string Privilized_Status { get; set; }
        public string Inventory_Entry_ItemCode_wise { get; set; }
        public string RecAdd { get; set; }
        public string RecEdit { get; set; }
        public string RecDel { get; set; }
    }
}
