//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Now
    {
        public string UserID { get; set; }
        public string comName { get; set; }
        public string loginTime { get; set; }
        public string IpAddress { get; set; }
    }
}
