//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Login
    {
        public string User_ID { get; set; }
        public string Password { get; set; }
        public string SecurityStamp { get; set; }
        public string User_Name { get; set; }
        public string Status { get; set; }
        public string PrjCode { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public string RecAdd { get; set; }
        public string RecDel { get; set; }
        public string RecEdit { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public string MobileNo { get; set; }
        public string Designation { get; set; }
        public string NID { get; set; }
        public string UserStatus { get; set; }
    }
}
