//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherNo
    {
        public decimal AutoSL { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string VoucherNo1 { get; set; }
        public Nullable<decimal> VoucherNo_Auto { get; set; }
        public string status { get; set; }
        public string UserID { get; set; }
        public string TransactionType { get; set; }
    }
}
