//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherName
    {
        public decimal Auto_SLNo { get; set; }
        public string VType { get; set; }
        public string Prefix { get; set; }
        public Nullable<decimal> Vou_OpeningNo { get; set; }
    }
}
