//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Order_Producer
    {
        public Nullable<decimal> DTSLNO { get; set; }
        public Nullable<System.DateTime> PDate { get; set; }
        public string PYear { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> VoucherNo_auto { get; set; }
        public Nullable<decimal> PrjCode { get; set; }
        public string CC_Name { get; set; }
        public string MLCNo { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Account_Sub_SubCode { get; set; }
        public Nullable<decimal> LedgerCode { get; set; }
        public Nullable<decimal> DrAmt { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string TransactionType { get; set; }
        public string Comments { get; set; }
        public string UserID { get; set; }
        public string ComputerName { get; set; }
        public string AddDate { get; set; }
        public string EditDate { get; set; }
        public string Cash_Cheque { get; set; }
        public string Dr_Cr { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Materila_Desc { get; set; }
        public string ClosingStatus { get; set; }
        public decimal Auto_SlNo { get; set; }
    }
}
