//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prac_mvc.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearClose
    {
        public Nullable<System.DateTime> Today { get; set; }
        public System.DateTime PDate { get; set; }
        public string UserID { get; set; }
        public string Notes { get; set; }
        public string PrjCode { get; set; }
    }
}
